-- MySQL Script generated by MySQL Workbench
-- Thu Oct 18 22:08:14 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
USE `goobus` ;

-- -----------------------------------------------------
-- Table `goobus`.`tbl_persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goobus`.`tbl_persona` (
  `cod_persona` INT NOT NULL AUTO_INCREMENT,
  `nombre_persona` VARCHAR(45) NOT NULL,
  `apellido_persona` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  PRIMARY KEY (`cod_persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goobus`.`tbl_tipo_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goobus`.`tbl_tipo_empleado` (
  `cod_empleado` INT NOT NULL AUTO_INCREMENT,
  `tipo_empleado` INT NOT NULL,
  PRIMARY KEY (`cod_empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table goobus.tbl_lugar
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS goobus.tbl_lugar (
  cod_lugar INT NOT NULL AUTO_INCREMENT,
  nombre_lugar VARCHAR(200) NOT NULL,
  descripcion VARCHAR(200) NULL,
  codigo_postal INT NULL,
  cod_lugar_hijo INT NULL,
  PRIMARY KEY (cod_lugar),
  CONSTRAINT fk_Lp_Lhijo
    FOREIGN KEY (cod_lugar_hijo)
    REFERENCES goobus.tbl_lugar (cod_lugar)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table goobus`.`tbl_empresa_transporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goobus`.`tbl_empresa_transporte` (
  `cod_empresa` INT NOT NULL AUTO_INCREMENT,
  `cod_lugar` INT NOT NULL,
  `nombre_empresa` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `cantidad_sucursal` INT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `dueño` VARCHAR(45) NOT NULL,
  `registro_operaciones` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_empresa`),
  CONSTRAINT `fk_empresa_lugar`
    FOREIGN KEY (`cod_lugar`)
    REFERENCES `goobus`.`tbl_lugar` (`cod_lugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goobus`.`tbl_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goobus`.`tbl_empleado` (
  `cod_persona` INT NOT NULL AUTO_INCREMENT,
  `tipo_empleado` INT NOT NULL,
  `cod_empresa` INT NOT NULL,
  `experiencia` VARCHAR(200) NULL,
  `foto` BLOB NOT NULL,
  PRIMARY KEY (`cod_persona`),
  CONSTRAINT `fk_empleado_persona`
    FOREIGN KEY (`cod_persona`)
    REFERENCES `goobus`.`tbl_persona` (`cod_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_tipoEmpleado`
    FOREIGN KEY (`tipo_empleado`)
    REFERENCES `goobus`.`tbl_tipo_empleado` (`cod_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_empresa`
    FOREIGN KEY (`cod_empresa`)
    REFERENCES `goobus`.`tbl_empresa_transporte` (`cod_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goobus`.`tbl_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goobus`.`tbl_usuario` (
  `cod_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(100) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cod_usuario`),
  CONSTRAINT `fk_usuario_persona`
    FOREIGN KEY (`cod_usuario`)
    REFERENCES `goobus`.`tbl_persona` (`cod_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goobus`.`TBL_Automotor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goobus`.`TBL_Automotor` (
  `cod_bus` INT NOT NULL AUTO_INCREMENT,
  `fk_cod_empresa` INT NOT NULL,
  `tipo_bus` VARCHAR(45) NOT NULL,
  `marca_bus` VARCHAR(45) NOT NULL,
  `color_bus` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_bus`),
  CONSTRAINT `fk_AUTOMOTOR_EMPRESA_TRANSPORTE1`
    FOREIGN KEY (`fk_cod_empresa`)
    REFERENCES `goobus`.`tbl_empresa_transporte` (`cod_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goobus`.`tbl_sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goobus`.`tbl_sucursal` (
  `cod_sucursal` INT NOT NULL AUTO_INCREMENT,
  `cod_empresa` INT NOT NULL,
  PRIMARY KEY (`cod_sucursal`),
  CONSTRAINT `fk_sucursal_empresa`
    FOREIGN KEY (`cod_empresa`)
    REFERENCES `goobus`.`tbl_empresa_transporte` (`cod_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goobus`.`tbl_marca_tarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goobus`.`tbl_marca_tarjeta` (
  `cod_marca` INT NOT NULL,
  `nombre_marca` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goobus`.`tbl_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goobus`.`tbl_pago` (
  `cod_pago` INT NOT NULL AUTO_INCREMENT,
  `cod_marca` INT NOT NULL,
  `num_tarjeta` VARCHAR(45) NULL,
  `fecha_vencimiento` DATE NULL,
  `ccv` INT NULL,
  `tipo_pago` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_pago`),
  CONSTRAINT `fk_pago_marca`
    FOREIGN KEY (`cod_marca`)
    REFERENCES `goobus`.`tbl_marca_tarjeta` (`cod_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goobus`.`HORA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goobus`.`HORA` (
  `cod_hora` INT NOT NULL AUTO_INCREMENT,
  `hora` TIME NOT NULL,
  `minutos` TIME NOT NULL,
  `segundos` TIME NOT NULL,
  PRIMARY KEY (`cod_hora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goobus`.`tbl_ruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goobus`.`tbl_ruta` (
  `cod_ruta` INT NOT NULL AUTO_INCREMENT,
  `cod_hora` INT NOT NULL,
  `cod_persona` INT NOT NULL,
  `cod_lugar` INT NOT NULL,
  `numero_asiento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_ruta`),
  CONSTRAINT `fk_RUTA_HORA1`
    FOREIGN KEY (`cod_hora`)
    REFERENCES `goobus`.`HORA` (`cod_hora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RUTA_EMPLEADO1`
    FOREIGN KEY (`cod_persona`)
    REFERENCES `goobus`.`tbl_empleado` (`cod_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RUTA_LUGAR1`
    FOREIGN KEY (`cod_lugar`)
    REFERENCES `goobus`.`tbl_lugar` (`cod_lugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goobus`.`tbl_boleto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goobus`.`tbl_boleto` (
  `cod_boleto` INT NOT NULL AUTO_INCREMENT,
  `USUARIO_cod_usuario` INT NOT NULL,
  `PAGO_cod_pago` INT NOT NULL,
  `RUTA_cod_ruta` INT NOT NULL,
  PRIMARY KEY (`cod_boleto`),
  CONSTRAINT `fk_boleto_ruta1`
    FOREIGN KEY (`RUTA_cod_ruta`)
    REFERENCES `goobus`.`tbl_ruta` (`cod_ruta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_boleto_usuario1`
    FOREIGN KEY (`USUARIO_cod_usuario`)
    REFERENCES `goobus`.`tbl_usuario` (`cod_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_boleto_pago1`
    FOREIGN KEY (`PAGO_cod_pago`)
    REFERENCES `goobus`.`tbl_pago` (`cod_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goobus`.`PRECIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goobus`.`PRECIO` (
  `cod_precio` INT NOT NULL AUTO_INCREMENT,
  `precio` DECIMAL NOT NULL,
  PRIMARY KEY (`cod_precio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goobus`.`tbl_empleado_bus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goobus`.`tbl_empleado_bus` (
  `cod_empl_bus` INT NOT NULL AUTO_INCREMENT,
  `cod_bus` INT NOT NULL,
  `cod_persona` INT NOT NULL,
  PRIMARY KEY (`cod_empl_bus`, `cod_bus`, `cod_persona`),
  CONSTRAINT `fk_bus_empleado`
    FOREIGN KEY (`cod_bus`)
    REFERENCES `goobus`.`TBL_Automotor` (`cod_bus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_automotor_empleado`
    FOREIGN KEY (`cod_persona`)
    REFERENCES `goobus`.`tbl_empleado` (`cod_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goobus`.`RUTA_X_EMPRESA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goobus`.`RUTA_X_EMPRESA` (
  `cod_ruta_empresa` INT NOT NULL AUTO_INCREMENT,
  `cod_ruta` INT NOT NULL,
  `cod_empresa` INT NOT NULL,
  PRIMARY KEY (`cod_ruta_empresa`, `cod_ruta`, `cod_empresa`),
  CONSTRAINT `fk_ruta_emoresa`
    FOREIGN KEY (`cod_ruta`)
    REFERENCES `goobus`.`tbl_ruta` (`cod_ruta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresa_ruta`
    FOREIGN KEY (`cod_empresa`)
    REFERENCES `goobus`.`tbl_empresa_transporte` (`cod_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goobus`.`tbl_automotor_ruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goobus`.`tbl_automotor_ruta` (
  `cod_ruta_bus` INT NOT NULL AUTO_INCREMENT,
  `cod_automotor` INT NOT NULL,
  `cod_ruta` INT NOT NULL,
  PRIMARY KEY (`cod_ruta_bus`, `cod_automotor`, `cod_ruta`),
  CONSTRAINT `fk_AUTOMOTOR_has_RUTA_AUTOMOTOR1`
    FOREIGN KEY (`cod_automotor`)
    REFERENCES `goobus`.`TBL_Automotor` (`cod_bus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AUTOMOTOR_has_RUTA_RUTA1`
    FOREIGN KEY (`cod_ruta`)
    REFERENCES `goobus`.`tbl_ruta` (`cod_ruta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goobus`.`RUTA_X_PRECIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goobus`.`RUTA_X_PRECIO` (
  `cod_ruta_precio` INT NOT NULL AUTO_INCREMENT,
  `cod_ruta` INT NOT NULL,
  `cod_precio` INT NOT NULL,
  PRIMARY KEY (`cod_ruta_precio`, `cod_ruta`, `cod_precio`),
  CONSTRAINT `fk_ruta_precio`
    FOREIGN KEY (`cod_ruta`)
    REFERENCES `goobus`.`tbl_ruta` (`cod_ruta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_precio_ruta`
    FOREIGN KEY (`cod_precio`)
    REFERENCES `goobus`.`PRECIO` (`cod_precio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `goobus` ;

-- -----------------------------------------------------
-- Table `goobus`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goobus`.`persona` (
  `cod_persona` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_persona` VARCHAR(45) NOT NULL,
  `apellido_persona` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `edad` INT(11) NOT NULL,
  PRIMARY KEY (`cod_persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `goobus`.`tipo_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `goobus`.`tipo_empleado` (
  `cod_empleado` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo_empleado` INT(11) NOT NULL,
  PRIMARY KEY (`cod_empleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
