-- MySQL Script generated by MySQL Workbench
-- Tue Oct 30 22:36:46 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gobus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gobus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gobus` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema sys
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sys
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sys` DEFAULT CHARACTER SET utf8 ;
USE `gobus` ;

-- -----------------------------------------------------
-- Table `gobus`.`tbl_genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gobus`.`tbl_genero` (
  `cod_genero` INT NOT NULL AUTO_INCREMENT,
  `genero` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`cod_genero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gobus`.`tbl_lugar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gobus`.`tbl_lugar` (
  `cod_lugar` INT NOT NULL AUTO_INCREMENT,
  `nombre_lugar` VARCHAR(200) NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `codigo_postal` INT NULL,
  `cod_lugar_hijo` INT NULL,
  PRIMARY KEY (`cod_lugar`),
  CONSTRAINT `fk_Lp_Lhijo`
    FOREIGN KEY (`cod_lugar_hijo`)
    REFERENCES `gobus`.`tbl_lugar` (`cod_lugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gobus`.`tbl_persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gobus`.`tbl_persona` (
  `cod_persona` INT NOT NULL AUTO_INCREMENT,
  `cod_genero` INT NOT NULL,
  `cod_lugar` INT NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `nombre_persona` VARCHAR(45) NOT NULL,
  `apellido_persona` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  PRIMARY KEY (`cod_persona`),
  CONSTRAINT `fk_tbl_persona_tbl_genero1`
    FOREIGN KEY (`cod_genero`)
    REFERENCES `gobus`.`tbl_genero` (`cod_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_persona_tbl_lugar1`
    FOREIGN KEY (`cod_lugar`)
    REFERENCES `gobus`.`tbl_lugar` (`cod_lugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gobus`.`tbl_tipo_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gobus`.`tbl_tipo_empleado` (
  `cod_empleado` INT NOT NULL AUTO_INCREMENT,
  `tipo_empleado` INT NOT NULL,
  PRIMARY KEY (`cod_empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gobus`.`tbl_empresa_transporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gobus`.`tbl_empresa_transporte` (
  `cod_empresa` INT NOT NULL AUTO_INCREMENT,
  `cod_lugar` INT NOT NULL,
  `nombre_empresa` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `cantidad_sucursal` INT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `dueño` VARCHAR(45) NOT NULL,
  `registro_operaciones` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_empresa`),
  CONSTRAINT `fk_empresa_lugar`
    FOREIGN KEY (`cod_lugar`)
    REFERENCES `gobus`.`tbl_lugar` (`cod_lugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gobus`.`tbl_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gobus`.`tbl_empleado` (
  `cod_persona` INT NOT NULL AUTO_INCREMENT,
  `tipo_empleado` INT NOT NULL,
  `cod_empresa` INT NOT NULL,
  `experiencia` VARCHAR(200) NULL,
  `foto` BLOB NOT NULL,
  PRIMARY KEY (`cod_persona`),
  CONSTRAINT `fk_empleado_persona`
    FOREIGN KEY (`cod_persona`)
    REFERENCES `gobus`.`tbl_persona` (`cod_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_tipoEmpleado`
    FOREIGN KEY (`tipo_empleado`)
    REFERENCES `gobus`.`tbl_tipo_empleado` (`cod_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_empresa`
    FOREIGN KEY (`cod_empresa`)
    REFERENCES `gobus`.`tbl_empresa_transporte` (`cod_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gobus`.`tbl_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gobus`.`tbl_usuario` (
  `cod_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` VARCHAR(100) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cod_usuario`),
  CONSTRAINT `fk_usuario_persona`
    FOREIGN KEY (`cod_usuario`)
    REFERENCES `gobus`.`tbl_persona` (`cod_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gobus`.`tbl_Automotor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gobus`.`tbl_Automotor` (
  `cod_bus` INT NOT NULL AUTO_INCREMENT,
  `fk_cod_empresa` INT NOT NULL,
  `tipo_bus` VARCHAR(45) NOT NULL,
  `marca_bus` VARCHAR(45) NOT NULL,
  `color_bus` VARCHAR(45) NOT NULL,
  `capacidad_asientos` INT NOT NULL,
  PRIMARY KEY (`cod_bus`),
  CONSTRAINT `fk_AUTOMOTOR_EMPRESA`
    FOREIGN KEY (`fk_cod_empresa`)
    REFERENCES `gobus`.`tbl_empresa_transporte` (`cod_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gobus`.`tbl_sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gobus`.`tbl_sucursal` (
  `cod_sucursal` INT NOT NULL AUTO_INCREMENT,
  `cod_empresa` INT NOT NULL,
  `descripcion` VARCHAR(200) NULL,
  `tbl_lugar_cod_lugar` INT NOT NULL,
  PRIMARY KEY (`cod_sucursal`, `tbl_lugar_cod_lugar`),
  CONSTRAINT `fk_sucursal_empresa`
    FOREIGN KEY (`cod_empresa`)
    REFERENCES `gobus`.`tbl_empresa_transporte` (`cod_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_sucursal_tbl_lugar1`
    FOREIGN KEY (`tbl_lugar_cod_lugar`)
    REFERENCES `gobus`.`tbl_lugar` (`cod_lugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gobus`.`tbl_marca_tarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gobus`.`tbl_marca_tarjeta` (
  `cod_marca` INT NOT NULL AUTO_INCREMENT,
  `nombre_marca` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gobus`.`tbl_empleado_bus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gobus`.`tbl_empleado_bus` (
  `cod_empl_bus` INT NOT NULL AUTO_INCREMENT,
  `cod_bus` INT NOT NULL,
  `cod_persona` INT NOT NULL,
  PRIMARY KEY (`cod_empl_bus`, `cod_bus`, `cod_persona`),
  CONSTRAINT `fk_bus_empleado`
    FOREIGN KEY (`cod_bus`)
    REFERENCES `gobus`.`tbl_Automotor` (`cod_bus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_automotor_empleado`
    FOREIGN KEY (`cod_persona`)
    REFERENCES `gobus`.`tbl_empleado` (`cod_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gobus`.`tbl_hora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gobus`.`tbl_hora` (
  `cod_hora` INT NOT NULL AUTO_INCREMENT,
  `hora` TIME NOT NULL,
  `minutos` TIME NOT NULL,
  `segundos` TIME NOT NULL,
  PRIMARY KEY (`cod_hora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gobus`.`tbl_ruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gobus`.`tbl_ruta` (
  `cod_ruta` INT NOT NULL AUTO_INCREMENT,
  `tbl_empleado_cod_persona` INT NOT NULL,
  `cod_hora` INT NOT NULL,
  `cod_lugar_origen` INT NOT NULL,
  `cod_lugar_destino` INT NOT NULL,
  PRIMARY KEY (`cod_ruta`),
  CONSTRAINT `fk_RUTA_HORA1`
    FOREIGN KEY (`cod_hora`)
    REFERENCES `gobus`.`tbl_hora` (`cod_hora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ruta_lugar`
    FOREIGN KEY (`cod_lugar_origen`)
    REFERENCES `gobus`.`tbl_lugar` (`cod_lugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_ruta_tbl_emple`
    FOREIGN KEY (`tbl_empleado_cod_persona`)
    REFERENCES `gobus`.`tbl_empleado` (`cod_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_ruta_tbl_lugar1`
    FOREIGN KEY (`cod_lugar_destino`)
    REFERENCES `gobus`.`tbl_lugar` (`cod_lugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gobus`.`tbl_ruta_x_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gobus`.`tbl_ruta_x_empresa` (
  `cod_ruta_empresa` INT NOT NULL AUTO_INCREMENT,
  `cod_ruta` INT NOT NULL,
  `cod_empresa` INT NOT NULL,
  PRIMARY KEY (`cod_ruta_empresa`, `cod_ruta`, `cod_empresa`),
  CONSTRAINT `fk_ruta_emoresa`
    FOREIGN KEY (`cod_ruta`)
    REFERENCES `gobus`.`tbl_ruta` (`cod_ruta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empresa_ruta`
    FOREIGN KEY (`cod_empresa`)
    REFERENCES `gobus`.`tbl_empresa_transporte` (`cod_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gobus`.`tbl_automotor_ruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gobus`.`tbl_automotor_ruta` (
  `cod_ruta_bus` INT NOT NULL AUTO_INCREMENT,
  `cod_automotor` INT NOT NULL,
  `cod_ruta` INT NOT NULL,
  PRIMARY KEY (`cod_ruta_bus`, `cod_automotor`, `cod_ruta`),
  CONSTRAINT `fk_bus_ruta`
    FOREIGN KEY (`cod_automotor`)
    REFERENCES `gobus`.`tbl_Automotor` (`cod_bus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bus_x_ruta`
    FOREIGN KEY (`cod_ruta`)
    REFERENCES `gobus`.`tbl_ruta` (`cod_ruta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gobus`.`tbl_boleto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gobus`.`tbl_boleto` (
  `cod_pago` INT NOT NULL,
  `cod_usuario` INT NOT NULL,
  `cod_ruta` INT NOT NULL,
  `cod_marca` INT NOT NULL AUTO_INCREMENT,
  `precio` FLOAT NOT NULL,
  `fecha_vencimiento` DATE NOT NULL,
  `impuesto` FLOAT NULL,
  `numero_asiento` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_pago`, `cod_usuario`, `cod_ruta`),
  CONSTRAINT `fk_tbl_usuario_tbl_ruta`
    FOREIGN KEY (`cod_usuario`)
    REFERENCES `gobus`.`tbl_usuario` (`cod_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_usuario_tbl_ruta1`
    FOREIGN KEY (`cod_ruta`)
    REFERENCES `gobus`.`tbl_ruta` (`cod_ruta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_pago_tbl_marca_tarjeta1`
    FOREIGN KEY (`cod_marca`)
    REFERENCES `gobus`.`tbl_marca_tarjeta` (`cod_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `sys` ;

-- -----------------------------------------------------
-- Table `sys`.`sys_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sys`.`sys_config` (
  `variable` VARCHAR(128) NOT NULL,
  `value` VARCHAR(128) NULL DEFAULT NULL,
  `set_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `set_by` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`variable`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
